[workspace]
resolver = "2"
members = [ "eight", "eleven", "fifteen", "five", "four", "fourteen", "nine","one", "seven", "six", "sixteen", "ten", "thirteen", "three", "twelve", "two"]

[workspace.dependencies]
